<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title><?php echo Zend_Registry::getInstance()->settings['site']['title']; ?> Backend</title>
<link rel="stylesheet" href="/css/backend/screen.css" type="text/css" media="screen" title="default" />
<link rel="stylesheet" href="/css/backend/jquery.qtip.min.css" type="text/css" media="screen, projection">
<link rel="stylesheet" href="/css/backend/jqtree.css" type="text/css" media="screen, projection">
<link rel="stylesheet" href="/css/backend/datatable.css" type="text/css" media="screen, projection">
<link rel="stylesheet" href="/css/backend/colorbox.css" type="text/css"	media="screen, projection">
<link rel="stylesheet" href="/css/backend/jcms.import.css" type="text/css"	media="screen, projection">
<script type="text/javascript" src="/js/backend/jquery-1.7.2.min.js"></script>
<script type="text/javascript" src="/js/backend/jquery-ui-1.8.19.custom.min.js"></script>
<script type="text/javascript" src="/js/backend/mouse.widget.coffee"></script>
<script type="text/javascript" src="/js/backend/simple.widget.coffee"></script>
<script type="text/javascript" src="/js/backend/tree.jquery.coffee"></script>
<script type="text/javascript" src="/js/backend/tree.jquery.js"></script>
<script type="text/javascript" src="/js/backend/jquery.qtip.min.js"></script>
<script type="text/javascript" src="/js/backend/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="/js/backend/jquery.colorbox-min.js"></script>
<script type="text/javascript" src="/tinymce/jscripts/tiny_mce/jquery.tinymce.js"></script>
<script type="text/javascript" src="/js/backend/jcms.js"></script>
<script type="text/javascript" src="/js/backend/jcms.import.js"></script>
<script type="text/javascript" src="/js/backend/jcms.qtiphelper.js"></script>
<script type="text/javascript">
	var tree = <?php echo jcms\Tree::getInstance()->getAsJson(); ?>;
  </script>
</head>
<body>
	<div id="section">
	  <div id="sectionHolder">
        <?php echo $this->layout()->content; ?>
      </div>
	</div>
	<div id="aside">
	<div class="filler-50"></div>
		<div id="tree"></div>
	</div>

	<div id="nav">
	<?php foreach($this->layout()->menu as $url=>$title){ ?>
      <ul class="select">
			<li class="current"><a href="<?php echo $url; ?>"
				title="<?php echo $title; ?>"><b><?php echo $title; ?></b></a></li>
		</ul>
    <?php } ?>
  </div>


</body>
</html>