<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <title>jCms</title>
  <link rel="stylesheet" href="/css/backend/screen.css" type="text/css" media="screen" title="default" />
  <script type="text/javascript" src="/js/backend/jquery-1.7.2.min.js"></script>
  <script type="text/javascript" src="/tinymce/jscripts/tiny_mce/jquery.tinymce.js"></script >
  <script type="text/javascript" src="/js/backend/jquery-ui-1.8.19.custom.min.js"></script>
  <script type="text/javascript" src="/js/backend/jquery.timepicker.js"></script>
  <link rel="stylesheet" href="/css/backend/dark-hive/jquery.ui.all.css" type="text/css" media="screen, projection">
</head>
<body class="iframe">

<?php echo $this->layout()->content; ?>

  <script type="text/javascript">
  $(function() {
		$('div.addcontent_objecttype_choice').click(function(){
			var id = $(this).attr('id');
			id = id.replace('objecttype_','');
			$('#objecttype_id').val(id);
			$('#content').submit();
		});
		bindEditor();
		$( "tr.datepicker > td > input" ).datetimepicker({ dateFormat: "dd-mm-yy", timeFormat: "hh:mm" }); //datepicker({ dateFormat: "dd-mm-yy h:m:s" });
	});

	function bindEditor(){
		$('textarea.tinymce').each(function(){
			var id = $(this).attr('id');
			$('#'+id).tinymce({
				// Location of TinyMCE script
				script_url : '/tinymce/jscripts/tiny_mce/tiny_mce.js',
				// General options
				theme : "advanced",
				plugins : "autolink,lists,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,advlist",
				// Theme options
				theme_advanced_buttons1 : "save,newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,styleselect,formatselect,fontselect,fontsizeselect",
				theme_advanced_buttons2 : "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",
				theme_advanced_buttons3 : "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen",
				theme_advanced_buttons4 : "insertlayer,moveforward,movebackward,absolute,|,styleprops,|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking,template,pagebreak",
				theme_advanced_toolbar_location : "top",
				theme_advanced_toolbar_align : "left",
				theme_advanced_statusbar_location : "bottom",
				theme_advanced_resizing : true,
				external_image_list_url : "/backend/clean/tinymceimages",
			    external_link_list_url : "/backend/clean/tinymcelinks",
			    relative_urls: false
			});
		});
	}

  </script>
</body>
</html>